deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        echo "CURSEFORGE_API_TOKEN=${{ secrets.CURSEFORGE_API_TOKEN }}" >> $GITHUB_ENV
        echo "PROJECT_ID=1119932" >> $GITHUB_ENV

    - name: Upload to CurseForge
      run: |
        curl -X POST "https://minecraft.curseforge.com/api/projects/$PROJECT_ID/upload-file" \
        -H "X-Api-Token: $CURSEFORGE_API_TOKEN" \
        -F "file=@target/my-plugin-1.0.jar" \
        -F "metadata={
              \"changelog\": \"Atualizações do plugin\",
              \"releaseType\": \"release\",
              \"gameVersions\": [\"1.17\", \"1.18\"]
            }"
